### ISSUE TITLE
Allow setting custom Garden Theme object

### ISSUE THREAD

**Issue by DocX** [zendeskgarden/tailwindcss#213]
We want to use custom garden theme, that we use also in the JS part. We use this theme dynamically - for dark / light theme switch.

Currently the plugin hardcodes the `DEFAULT_THEME` from garden. Is there a way to configure custom theme, and generate two sets of CSS? So we can switch between one and second theme?

**Comment by jzempel** [comment]
Garden recommends [overriding the default theme](https://tailwindcss.com/docs/theme#overriding-the-default-theme) via Tailwind.
