### ISSUE TITLE
Investigate providing utility CSS build for non-PostCSS consumers

### ISSUE THREAD

**Issue by austingreendev** [zendeskgarden/tailwindcss#22]
## Description

The current tailwindcss plugin only provides a Tailwind plugin. This removed the ability for consumers to directly include styling without a build process.

## Detail

To help with this we can investigate providing a pre-built CSS file for consumers. This file could live in `dist/utilities.css` and be referenced by a consumer if necessary.

Some pitfalls of this could include:
- Determining a correct level of browser support as Tailwind uses some modern syntax
- Documenting the potentially large size-increase using this method as Tailwind includes many more style utilities than we have handled in the past

**Comment by jzempel** [comment]
I like this. Should we target `dist/index.css` as we have in `css-components`?
